name: Generate Snake Game

on:
  schedule:
    - cron: "0 */24 * * *"   # runs every 24 hours
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Generate Snake SVGs
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: rick018-cyber
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light

      # 3. Push Snake SVGs to output branch
      - name: Push snake files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output    # branch to store Snake files
          build_dir: dist
          keep_files: true         # preserves existing files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
